apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch-claim0
  name: elasticsearch-claim0
spec:
  storageClassName: elastic
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
status: {}
