apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kibana-claim0
  name: kibana-claim0
spec:
  storageClassName: kibana
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
status: {}
